relay: delay creating aiohttp.ClientSession
- create aiohttp.ClientSession on asyncio thread, as required by aiohttp 3.11
- minor fixes for object lifecycles (make sure objects are cleaned-up)

```
 10.28 | E | gui.qt.exception_window.Exception_Hook | exception caught by crash reporter
Traceback (most recent call last):
  File ".../electrum/electrum/gui/qt/channels_list.py", line 370, in <lambda>
    menu.addAction(read_QIcon('update.png'), _('Submarine swap'), lambda: self.main_window.run_swap_dialog())
  File ".../electrum/electrum/gui/qt/main_window.py", line 1175, in run_swap_dialog
    transport = self.create_sm_transport()
  File ".../electrum/electrum/gui/qt/main_window.py", line 1207, in create_sm_transport
    return sm.create_transport()
  File ".../electrum/electrum/submarine_swaps.py", line 270, in create_transport
    return NostrTransport(self.config, self, keypair)
  File ".../electrum/electrum/submarine_swaps.py", line 1355, in __init__
    self.relay_manager = aionostr.Manager(self.relays, private_key=self.nostr_private_key, log=self.logger, ssl_context=ssl_context)
  File ".../electrum-aionostr/src/electrum_aionostr/relay.py", line 179, in __init__
    self.client = ClientSession(connector=proxy)
  File ".../Python310/site-packages/aiohttp/client.py", line 310, in __init__
    loop = loop or asyncio.get_running_loop()
RuntimeError: no running event loop
```